#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Keith Analytics 

# Short bio or description (displayed in the header)
description: The rate of data collection is ever-increasing, and so too is the size of databases and data warehouses. This presents an enormous opportunity to identify hidden value and enable data-driven decision-making. However, this opportunity often goes unrealised because either the potential is unidentified, or the process by which it could be implemented is never pursued. I bring my extensive data-science and machine-learning expertise to help clients identify opportunities, develop an implementation plan, and engineer productionised solutions - either as a consultant, or as a contractor collaborating with the client's developer team. 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://github.com/wall0159/wall0159.github.io/blob/master/images/keith_analytics_long_logo.png 
avatar: http://keith-analytics.com.au/images/angus_zoom.jpg
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: wallace.angus@gmail.com
  facebook:
  flickr:
  github: 
  instagram:
  linkedin: https://www.linkedin.com/in/angus-wallace-5b375113
  pinterest:
  rss: true # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: keith-analytics.com.au

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
